export const SERVER_ERROR = 'SERVER_ERROR';

// tx-data
export const UPLOAD_TX_DATA_SUCCESS = 'UPLOAD_TX_DATA_SUCCESS';
export const FETCH_TX_DATA_SUCCESS = 'FETCH_TX_DATA_SUCCESS';
export const FETCHALL_TX_DATA_SUCCESS = 'FETCHALL_TX_DATA_SUCCESS';

// tx-rules
export const FETCHALL_STRING_RULES_SUCCESS = 'FETCHALL_STRING_RULES_SUCCESS';
